apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kubernetes.io/change-cause: "liberación de versión con número de compilacion {{BUILD_NUMBER}}"
  name: devsu-demo-deploy
  namespace: devsu
  labels:
    app: devsu-demo
spec:
  replicas: 2
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: devsu-demo
  template:
    metadata:
      namespace: devsu
      labels:
        app: devsu-demo
    spec:
      containers:
        - name: devsu-demo
          image: oscarcalvache/devsu-demo:{{BUILD_NUMBER}}
          ports:
            - containerPort: 8000
          resources:
            requests:
              memory: "256Mi"
              cpu: "0.5"
          livenessProbe:
            httpGet:
              path: /api/health
              port: 8000
            initialDelaySeconds: 30
            periodSeconds: 10
